# Generated by Django 4.2 on 2024-09-20 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("course_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("thumbnail_pic_link", models.URLField()),
                ("certificate_preview_link", models.URLField()),
                ("number_of_ratings", models.IntegerField(default=0)),
                ("course_level", models.CharField(max_length=50)),
                ("Rate", models.FloatField(default=0.0)),
                ("points_providing", models.IntegerField(default=0)),
                ("Enrollment_Counts", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("profilePic", models.URLField(blank=True, null=True)),
                ("birthDate", models.DateTimeField(blank=True, null=True)),
                ("signedUpAt", models.DateTimeField(auto_now_add=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("resetToken", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "refreshToken",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("numberOfQuestionsSolved", models.IntegerField(default=0)),
                ("correctQuestions", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
            ],
        ),
    ]
