# Generated by Django 4.2 on 2024-09-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("chapterId", models.IntegerField()),
                ("videoLink", models.CharField(max_length=255)),
                ("likesCount", models.PositiveIntegerField(default=0)),
                ("dislikesCount", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("chapter_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="analytics.course",
                    ),
                ),
            ],
        ),
    ]
